### ISSUE TITLE
Add Wide/Horizontal card support

### ISSUE THREAD

**Issue by svalencia014** [dailydotdev/action-devcard#405]
Would be great to be able to use the horizontal or "wide" version of the card

**Comment by iamncdai** [comment]
Great, my wish is the same as yours. I have created a Pull Request, which supports Vertical/Horizontal. Hope to be accepted soon.

https://github.com/dailydotdev/action-devcard/pull/406

**Comment by iamncdai** [comment]
Hi @svalencia014 ,

You can configure the devcard's orientation. For example:

```yaml
name: daily-devcard
on:
   workflow_dispatch:
   push:
     branches:
       - main
   schedule:
     - cron: "0 0 * * *"
jobs:
   devcard:
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
       - name: devcard
         uses: dailydotdev/action-devcard@3.1.0
         with:
           user_id: ${{ secrets.USER_ID }}
           type: "wide"
           commit_message: "chore: update ${filename}"
```
